fakepay:

  adapter:

    realex:
      class: \FakePay\Adapter\RealexAdapter
      merchant_id:  %realex.merchant_id%
      secret:       %realex.secret%
      response_url: %realex.response_url%

    realvault:
      class: \FakePay\Adapter\RealvaultAdapter
      merchant_id:  %realex.merchant_id%
      secret:       %realex.secret%
      response_url: %realex.response_url%


    sagepay:
      class: \FakePay\Adapter\RealexAdapter
